# Generated by Django 4.0.5 on 2022-06-27 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kndi_number', models.CharField(max_length=200, unique=True)),
                ('speciality', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20, null=True)),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=True, help_text='select above', max_length=20)),
                ('patient_age', models.CharField(max_length=20)),
                ('date_created', models.DateField(verbose_name='entry date (2022/mm/dd)')),
                ('supervisor_contact', models.CharField(max_length=20, null=True)),
                ('hospital', models.CharField(max_length=200)),
                ('biochemistry_results', models.BooleanField(null=True)),
                ('nutrition_diagnosis', models.CharField(blank=True, max_length=1000)),
                ('services_rendered', models.CharField(blank=True, max_length=300)),
                ('clinical_diagnosis', models.BooleanField(null=True)),
                ('follow_up_plan', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=2000)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.profile')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
