# Generated by Django 3.1.7 on 2022-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kndi_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
