# Generated by Django 3.1.7 on 2022-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0005_auto_20220727_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookdata',
            name='hospital',
            field=models.CharField(choices=[('H', 'AAR Hospital'), ('H', 'Aga Khan University Hospital, Nairobi['), ('H', 'Avenue Hospital'), ('H', 'Bristol Park Hospital Tasia Embakas'), ('H', 'Brother André Medical Center in Dandora'), ('H', 'Coptic Hospital Nursing Hospital'), ('H', "Gertrude's Children's Hospital"), ('H', 'Karen Hospital'), ('H', 'Kenyatta Hospital'), ('H', 'Mama Lucy Kibaki'), ('H', 'Mater Hospital')], max_length=200),
        ),
    ]
