# Generated by Django 3.1.7 on 2022-07-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookdata', '0006_auto_20220727_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logbookdata',
            name='hospital',
            field=models.CharField(choices=[('H', 'AAR Hospital'), ('H', 'Aga Khan University Hospital, Nairobi'), ('H', 'Avenue Hospital'), ('H', 'Bristol Park Hospital Tasia Embakas'), ('H', 'Brother André Medical Center in Dandora'), ('H', 'Coptic Hospital Nursing Hospital'), ('H', "Gertrude's Children's Hospital"), ('H', 'Karen Hospital'), ('H', 'Kenyatta Hospital'), ('H', 'Mama Lucy Kibaki'), ('H', 'Mater Hospital')], max_length=200),
        ),
    ]
